### PR TITLE
master-qa-34099

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-34099

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
cc @GinsonRen

**Comment by GinsonRen** [comment]
@SylviaLuan 
Please use Polls.viewVotedPollPG in viewPollOnLivingSite directly and move the navigator to live site into testcase. Thanks.

**Pull request closed without merging**
