### PR TITLE
master-qa-28785

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-28785

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:retest

**Comment by Hanlf** [comment]
ci:retest

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44518
https://github.com/brianchandotcom/liferay-portal/pull/44519

**Comment by brianwulbern** [comment]
@Hanlf  @GinsonRen please close this pull.  Thanks!

**Pull request closed without merging**
