### PR TITLE
LPS X InetAddressUtil 2

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-X The AtomicInteger should be a field, otherwise the limit won't work
- LPS-X Use a ThreadPoolExecutor to implement the limitation: 1) 1 core thread, max DNS_SECURITY_THREAD_LIMIT threads; 2) no work queue; 3) keeping the original logic when rejected (return null)
- LPS-X Cache the resolved InetAddress; TODO: cache expiration

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the CI results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@GinsonRen I sent it to https://github.com/liferay-core-infra/liferay-portal/pull/853, the additional commits are not performance related.

**Comment by 111Anna** [comment]
@dantewang @GinsonRen  I ran it on main1 env, here are results:

Login:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a24ee1a | 51662 | 289 | -
PR-617 | - | 52576 | 277 | 1.77%

WC:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a24ee1a | 70196 | 407 | -
PR-617 | - | 69058 | 466 | -1.6%

MB：

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a24ee1a | 10526 | 802 | -
PR-617 | - | 10714 | 96.2 | 1.79%

Blog:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a24ee1a | 6911 | 15.6 | -
PR-617 | - | 6911 | 15.4 | 0%

DL:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a24ee1a | 29271 | 448 | -
PR-617 | - | 31311 | 423 | 6.97%

AP:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a24ee1a | 26052 | 377 | -
PR-617 | - | 24645 | 368 | -5.4%

**Pull request closed without merging**
