### PR TITLE
master-qa-47782

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-47782

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72953

**Pull request closed without merging**
