### PR TITLE
master-qa-43353

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-43353

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @yuwanyang 
- Update case name.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65200

**Pull request closed without merging**
