### PR TITLE
LRQA-42228,  LRQA-41998 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-42228
https://issues.liferay.com/browse/LRQA-41998

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test

**Comment by liulukiwi** [comment]
Hi @GinsonRen ， the failed case is not related to the commits.

**Comment by GinsonRen** [comment]
SF for @suilin 
Re-order the locators.

/cc @liulukiwi

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/61384

**Pull request closed without merging**
