### PR TITLE
master-qa 43373

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-43373

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
cc @brianwulbern

**Comment by suilin** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @suilin 

- Remove unnecessary steps.
- Add assertion for console output.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64940

**Pull request closed without merging**
