### PR TITLE
LPS X Performance 1

### PR DESCRIPTION
**Pull request by dantewang**
@GinsonRen Please run a performance comparison, thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
FYI @yuhai @slnn

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@GinsonRen Please hold this test. One of the elements is not available on the page, which may cause false positive in performance increase. I'll need to double check.

**Comment by dantewang** [comment]
@GinsonRen Fixed, please run a diff for this, thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@dantewang Here is the result:


Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BASELINE (2022-3-14 master head) | e34290f69c2 | 43032 | 267 |  
LPS-X-Performance-1 | https://github.com/GinsonRen/liferay-portal/pull/585 | 42103 | 274 | -2.16%

**Comment by dantewang** [comment]
@GinsonRen Hmm strange, it should not be a regression at least.. Could you make a profile for your baseline and the PR?

**Comment by dantewang** [comment]
@GinsonRen Could you run a diff for this commit only: https://github.com/GinsonRen/liferay-portal/pull/585/commits/cd2fe621827bcc79d38f4c5699c483583fd91933?

**Pull request closed without merging**
