### PR TITLE
master-qa-50419

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-50419

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
@GinsonRen it can be cherry pick to 7.2.x

**Comment by GinsonRen** [comment]
Hi @melodywu 

When the initialized variable and asserted variable are conflict, we prefer to update the assert variable to keep the case to test the original function. Please re-send your fix, thanks.

**Pull request closed without merging**
