### PR TITLE
master-qa-43351

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-43351

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @Songyuewen ,

- Add a mew macro editConfigureTagsFilterPG.
- Remove the duplicate locator "FILTER_QUERY_AND_OPERATOR".

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65570

**Pull request closed without merging**
