### PR TITLE
LPS X MB 1

### PR DESCRIPTION
**Pull request by dantewang**
@GinsonRen Please run a performance comparison for MB. This reduces a little bit of invocations from both portal and database side.

### CODE REVIEW

**Comment by dantewang** [comment]
cc @yuhai @slnn

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by GinsonRen** [comment]
@dantewang I run the test with "sample.repeattimes=10", as you konw, the longer test run, the more unstable session count. The session count of sample 8 is 11660.

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | 0a0e39d | 11747 | 699 | -
dantewang:LPS-X-MB-1 | https://github.com/GinsonRen/liferay-portal/pull/602 | 11170 | 1630 | -4.91%

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the CI results? Thanks!

**Comment by dantewang** [comment]
@GinsonRen Force pushed with some extra change. Please run it on both qa env and one of the main envs. Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 Force pushed with extra change, I will re-run the tests.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
The failures should be unrelated.

**Comment by zhangyan0701** [comment]
Checked the new results, no related failures.

**Comment by GinsonRen** [comment]
@dantewang Here is the reuslt on main2:

Portal version | Git ID/PR link | Session count | Meantime of Login | Meantime of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage (%) | Session Count Change compare to baseline（%）
-- | -- | -- | -- | -- | -- | -- | --
BaseLine(4-27 master head) | a68e36aa26811402986b78a3cb69295032820417 | 11172 | 151 | 162 | 10,17,68 | 27,28,27 |  
LPS-X-MB-1 | https://github.com/GinsonRen/liferay-portal/pull/602 | 11217 | 54.2 | 84.3 | 10,20,67 | 27,28,27 | 0.40%

**Comment by 111Anna** [comment]
@dantewang  Here is the reuslt on qa1:

Portal version | Git ID/PR link | Session count | Meantime of Login | Meantime of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage (%) | Session Count Change compare to baseline（%）
-- | -- | -- | -- | -- | -- | -- | --
BaseLine(4-27 master head) | a68e36a | 6508 | 94.6 | 254 | 13,15,17 | 90,93,93 |  -
LPS-X-MB-1 | #602 | 6629 | 127 | 306 | 14,16,18 | 93,93,93 | 1.86%

**Pull request closed without merging**
