### PR TITLE
[Login-performance-tuning] LPS-X8

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, please run one performance test. But I think you may take this as the low priority because it should only have a little improvement.

cc @dantewang @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@yuhai Here is the result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BASELINE (2022-3-14 master head) | e34290f69c2 | 42375 | 273 |  
LPS-X8 | https://github.com/GinsonRen/liferay-portal/pull/593 | 42265 | 264 | -0.26%

**Comment by yuhai** [comment]
@GinsonRen. thanks. Send it to https://github.com/liferay-core-infra/liferay-portal/pull/563

**Pull request closed without merging**
