### PR TITLE
LRQA-51487, LRQA-51485 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-51487
https://issues.liferay.com/browse/LRQA-51487
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77420

**Pull request closed without merging**
