### PR TITLE
master-qa-45197

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-45197

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@suilin 

- Please use sitePages.configurePage instead of configureWidgetPageTemplateLayout.
- SitePages._addPage already include  inheritChanges, please set inheritChanges as a var for it instead add a extra step.

Please re-send your fix, thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66305

**Pull request closed without merging**
