### PR TITLE
master-qa-48287

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-48287
https://issues.liferay.com/browse/LRQA-48284
https://issues.liferay.com/browse/LRQA-48296

@GinsonRen
Commits are only for master, thanks.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71574

**Pull request closed without merging**
