### PR TITLE
LRQA-37087 | Master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-37087

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:test

**Comment by brianwulbern** [comment]
ci:test

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
Failures are due to a [change in UI](https://github.com/brianchandotcom/liferay-portal/pull/54370/commits/d86ce981a59dd9ea46b4b3e401936e7248a79960) in the User Edit page.

[Testray results](https://testray.liferay.com/home/-/testray/case_results?statuses=4%2C3%2C1%2C7%2C0&testrayRunId=146801637)

Albert is sending a fix now.

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BWulbern.
https://github.com/brianwulbern/liferay-portal/pull/208

**Pull request closed without merging**
