### PR TITLE
master-qa-51045

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-51045

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76445

**Pull request closed without merging**
