### PR TITLE
master-qa-48428

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-48428
master only

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Comment by GinsonRen** [comment]
@yunlinsun 

I just updated the locator for making it more efficient. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71766/

**Pull request closed without merging**
