### PR TITLE
master-qa-50897

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-50897
Can be cherry pick to 7.2

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by HarryC0204** [comment]
This case can be cherry pick to 7.2 @GinsonRen

**Comment by GinsonRen** [comment]
No test changes needed :)

**Pull request closed without merging**
