### PR TITLE
[Login-performance-tuning] LPS-X9 

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, please run login performance test.

cc @dantewang, @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@yuhai I ran two times, here are the result, I already upload the profile to amazon cloud.


Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BASELINE (2022-3-14 master head) | e34290f69c2 | 42375 | 273 |  
LPS-X9 | https://github.com/GinsonRen/liferay-portal/pull/594 | 39819 | 265 | -6.03%
LPS-X9 | https://github.com/GinsonRen/liferay-portal/pull/594 | 40508 | 255 | -4.41%

**Comment by yuhai** [comment]
@GinsonRen, thanks for your test. I compared the profile **profile-master-login-2022-03-14-12-15-30-e34290f69c22b81290864b086851386216bb9605** with **profile-LPS-X9-login-2022-03-29-18-26-24-9cd03d64a6c8998f0a49e614347abe4762522de6**. I find my change can reduce related method run times. Please refer to the below pics.
03-14


03-29


Could you please run the test again in the same server?

Thanks.
Hai

**Comment by GinsonRen** [comment]
@yuhai I rebuild-DB on main2 and re-run the test, here is the result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BASELINE (2022-3-14 master head) | e34290f69c2 | 39515 | 262 |  
LPS-X9 | https://github.com/GinsonRen/liferay-portal/pull/594 | 39871 | 261 | 0.90%

**Comment by yuhai** [comment]
@GinsonRen, thanks

**Pull request closed without merging**
