### PR TITLE
[DL tuning] LPS-DL2 

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, please run one DL performance test. Thanks.

cc @dantewang, @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@yuhai 

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-19 master head) | 2952e2402a5a55bfc54ffbe54512fdf68f4b3b4d | 30139 | 415 |  
yuhai:LPS-DL2 | https://github.com/GinsonRen/liferay-portal/pull/613 | 31155 | 309 | 3.37%

**Comment by yuhai** [comment]
@GinsonRen, I find LPS-153703's fix should decrease the 1/3 of the test result. That is to say, the test result may be 2%+, could you please check this on the latest master? Thanks.

cc @dantewang, @slnn

**Comment by GinsonRen** [comment]
@yuhai 

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-23 master head) | 3668282 | 29356 | 456 |  
yuhai:LPS-DL2 | https://github.com/GinsonRen/liferay-portal/pull/613 | 29658 | 475 | 1.03%

**Comment by yuhai** [comment]
@GinsonRen, thanks. Send it to https://github.com/liferay-core-infra/liferay-portal/pull/816 to review.

cc @dantewang,

**Pull request closed without merging**
