### PR TITLE
master-qa-43354

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-43354

cc @brianwulbern

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @JoyceWang08211 
-  Update case name.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65200

**Pull request closed without merging**
