### PR TITLE
master-qa-50187

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-50187

Able to cherry-pick to 72

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76195

**Pull request closed without merging**
