### PR TITLE
master-qa-48851

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-48851

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @Songyuewen 

I just updated the priority as 3.

**Comment by GinsonRen** [comment]
Pushed to AChiang.
https://github.com/austinchiang/liferay-portal/pull/384

**Pull request closed without merging**
