### PR TITLE
[Login-performance-tuning] LPS-X4

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, the pr is based on https://github.com/GinsonRen/liferay-portal/pull/596.  Please run one login performance test based on the latest master. Thanks.

cc @dantewang, @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@yuhai Here is the result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | 77f3657 | 40221 | 274 |  
LPS-X4-pr3 | https://github.com/GinsonRen/liferay-portal/pull/597 | 42201 | 268 | 4.92%

**Comment by yuhai** [comment]
@GinsonRen, thanks. Send it to https://github.com/liferay-core-infra/liferay-portal/pull/566 to review.

**Pull request closed without merging**
