### PR TITLE
master-qa-43377

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-43377

cc @brianwulbern

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@zhangyan0701 @GinsonRen 

probably don't need to view the title [here](https://github.com/GinsonRen/liferay-portal/pull/265/commits/b201052f3ea49459ff63375b75d33e66aa1ac5d9#diff-84552cb4e46cd59bb403c2494db5675fR1985), the rest looks fine.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64833

**Pull request closed without merging**
