### PR TITLE
master-qa-36760

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-36760

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test

**Comment by JoyceWang08211** [comment]
ci:test

**Comment by JoyceWang08211** [comment]
ci:retest

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BWulbern.
https://github.com/brianwulbern/liferay-portal/pull/206

**Pull request closed without merging**
