### PR TITLE
master-qa-43369

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-43369

### CODE REVIEW

**Comment by yuwanyang** [comment]
cc @brianwulbern

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@yuwanyang looks like there's a rebase error:

```
Conflicting files
portal-web/test/functional/com/liferay/portalweb/tests/enduser/wcm/staging/usecase/Staging.testcase
```

Not sure if you'd be asked to fix it, or if @GinsonRen does it.

**Comment by GinsonRen** [comment]
@brianwulbern  Thanks for catch this.

@yuwanyang Please re- send your fix after rebase your code. Thanks.

**Pull request closed without merging**
