### PR TITLE
master-qa-41034

### PR DESCRIPTION
**Pull request by felix3508**
https://issues.liferay.com/browse/LRQA-41034

### CODE REVIEW

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@felix3508 Please look into the SF error and re-send your fix. Thanks.

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test:relevant

**Pull request closed without merging**
