### PR TITLE
master-qa-42523

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-42523

### CODE REVIEW

**Comment by yuwanyang** [comment]
cc @brianwulbern

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@yuwanyang don't need [to declare this](https://github.com/GinsonRen/liferay-portal/pull/267/commits/776b020e2f2dbd4564a47248c7290e2539f0c472#diff-0a64fae89c0f366019fa5215a732fe71R63) without a key_var in the locator

cc @GinsonRen

**Pull request closed without merging**
