### PR TITLE
master-qa-42523

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-42523

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@yuwanyang 

- Variable declaration of BlogsEntry.macro in line 63 is unnecessary.
- AssertClick and AssertTextEquals#assertPartialText are duplicate step because assertclick alreday include assert and click,
- Please keep consistent between "externalLink" and "externalLURL" in macro addEntryExternalLink and viewEntry.
- Add new <if> condition to viewEntry for view external link.
- Just use original variable "EntryContent" instead of add new one "entryExternalLink".
- Please update the test command name.

Please re-send your fix, thank you.

**Pull request closed without merging**
