### PR TITLE
master-qa-51593

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-51593
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@melodywu 

- Why did you change the variable name from selectOption to fieldValue? 
- Please separated your commit.
- Please re-upload report after your change your fix.
- Please re-run ci:test:sf after you push force for fix SF. Still have extra space in your FormsAdmin.macro.

Please re-send your fix, thank you.

**Pull request closed without merging**
