### PR TITLE
7.0.x-qa-29422

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-29422

### CODE REVIEW

**Comment by brianwulbern** [comment]
SF for @Sharryxue 

* Changed the macro name to mention that it's a _specific_ email
* Moved one email deletion up to right when the email is no longer needed
* Applied the fix to another Reports test
* Ran `ant format-source-current-branch` and that moved your gmail code block to where it should be alphabetically (make sure to run `ant -f build-test.xml run-poshi-validation` *and* `ant format-source-current-branch` before you send pulls)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45892
https://github.com/brianchandotcom/liferay-portal/pull/45893

**Comment by brianwulbern** [comment]
@Sharryxue @GinsonRen please close this pull.  Thanks!

**Comment by Sharryxue** [comment]
@brianwulbern 
Got it, thanks.

**Pull request closed without merging**
