### PR TITLE
LRQA-42023 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-42023

cc/ @brianwulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64833

**Pull request closed without merging**
