### PR TITLE
master-qa-48360

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-48360

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
@GinsonRen this can be cherry pick to 7.2.x.

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78107

**Pull request closed without merging**
