### PR TITLE
master-qa-34400

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-34400

### CODE REVIEW

**Comment by Sharryxue** [comment]
Sorry for the SF issue, resolved on local and force updated here.

**Comment by GinsonRen** [comment]
ci:test

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BWulbern.
brianwulbern#200

**Pull request closed without merging**
