### PR TITLE
master-qa-43369

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-43369

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @yuwanyang 
Move the case to staging#PublishRenamedTags.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65069

**Pull request closed without merging**
