### PR TITLE
null out implementation

### PR DESCRIPTION
**Pull request by drewbrokke**
Hi Ginson, this change is to verify whether or not this class is responsible for the performance regression I got an email about.<br/><br/>/cc @tinatian

### CODE REVIEW

**Comment by GinsonRen** [comment]
@drewbrokke  Anna and I will test this tomorrow. Thank you.
/cc @111Anna

**Comment by GinsonRen** [comment]
@drewbrokke We are working on white paper testing of 74x which is high priority. We will test this sometime next week. Sorry for that.

**Comment by drewbrokke** [comment]
No worries, thank you for the update @GinsonRen!

**Comment by 111Anna** [comment]
@drewbrokke  We are testing master. It has a problem. We will test this next week. I'm very sorry.
/cc @GinsonRen

**Comment by 111Anna** [comment]
@drewbrokke This change fixes our performance regression. Thank you.
/cc @GinsonRen

**Comment by 111Anna** [comment]
The previously tested environment (main1) is testing something else, I can only change another set of environment qa2, but the hardware configuration of qa2 is not as high as main1, so the comparison on login is not obvious, so I retest it with wiki.

N/A|Git Id|Session count |Mean Time Login|Mean Time Add Wiki Page
:-|:-:|:-:|:-:|:-:
Before-LPT-141798|b6628f3b8de48|4244|184|799
LPT-141798|3d11a6abf1da0|3988|500|1240
Add this change|81478b36c4d2|4226|193|874

From the test results of wiki, this change is useful. If necessary, we can test it again when environment (main1) is free.

**Pull request closed without merging**
