### PR TITLE
master-qa-47578

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-47578

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Sf for @melodywu 

- Update priority to 3.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72744

**Pull request closed without merging**
