### PR TITLE
LPS-X-DL-2 Shortcut earlier if don't show actions

### PR DESCRIPTION
**Pull request by dantewang**
@GinsonRen Please run DL diff for it, thanks! cc @slnn @yuhai

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:document

**Comment by GinsonRen** [comment]
@dantewang 

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-12 master head) | d82674bf6b0e14486ad224f38de4258a80a44f88 | 29757 | 547 |  
LPS-X-DL-2 | https://github.com/GinsonRen/liferay-portal/pull/611 | 30457 | 442  | 2.35%

**Comment by zhangyan0701** [comment]
The ci test failures are unrelated.

**Pull request closed without merging**
