### PR TITLE
master-qa-51327

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-51327
Please cherry-pick to 7.2.x, thanks.

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
ci:help

**Comment by GinsonRen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77720

**Pull request closed without merging**
