### PR TITLE
master-qa-47782

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-47782

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
Hi @melodywu ,

- Please update your commit message like "Add new test for ...".
- Please update your test case name more clear,
- Please add a space after the punctuation in description.

Please re-send your fix, thanks.

**Pull request closed without merging**
