### PR TITLE
master-qa-48295

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-48295
master only

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
cc @brianwulbern

**Comment by brianwulbern** [comment]
ci:help

**Comment by GinsonRen** [comment]
SF for @SylviaLuan 

- Adding line break.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71834

**Pull request closed without merging**
