### PR TITLE
master-qa-51593

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-51593
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @melodywu 
Maybe we can use AssertNotVisable instead of AssertElementNotPresent, if the reviewer is not support to see the submit button. Please re-send your fix, thanks.

**Pull request closed without merging**
