### PR TITLE
LRQA-41986, LRQA-41991 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-41986
https://issues.liferay.com/browse/LRQA-41991

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/61058
https://github.com/brianchandotcom/liferay-portal-ee/pull/20869

**Comment by GinsonRen** [comment]
SF for @JoyceWang08211 

- Use <isset>  instead of <equals> since there is no false value.
- Use "update" as var name.

**Comment by GinsonRen** [comment]
@HarryC0204 LRQA-41986 will be fixed on https://github.com/brianchandotcom/liferay-portal/pull/61058

**Pull request closed without merging**
