### PR TITLE
master-qa-42917

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-42917

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @liuxingye 

-  Use the existing macro instead creating one.
- Remove the unnecessary locators.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64828

**Pull request closed without merging**
