### PR TITLE
LRQA-42234, LRQA-42235, LRQA-42242 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-42234
https://issues.liferay.com/browse/LRQA-42235
https://issues.liferay.com/browse/LRQA-42242

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/61244

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/61244

**Pull request closed without merging**
