### PR TITLE
master-qa-21250

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-21250

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:retest

**Comment by liuxingye** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for BLiu @liuxingye:

* While there aren't any Organizations yet created where you updated the tests, we're not concerned as much with whether there are Organizations present in these tests, so we can use the simpler navigation (for reference, a test that _is_ concerned with the presence of an existing Organization is: CPUsersandorganizations#DeleteOrganization).  Let me know if that doesn't make sense.  Thanks!

**Comment by brianwulbern** [comment]
@liuxingye you can close this pull when you get a chance, thanks!

**Comment by brianwulbern** [comment]
Pushed to ENagayama.
https://github.com/evannagayama/liferay-portal/pull/726

**Comment by brianwulbern** [comment]
So quick!

**Comment by liuxingye** [comment]
@brianwulbern 
I have tried to execute your SF on my local environment, but it can't be passed.
The command of 'gotoOrganizations' contains the following information. 
--------------------------------------------------------------------------------------------------
<command name="gotoOrganizations">
	<execute function="Pause" locator1="1000" />

	<if>
		<condition function="IsElementPresent" locator1="NavBar#ORGANIZATIONS" />
		<then>
			<execute function="AssertClick" locator1="NavBar#ORGANIZATIONS" value1="Organizations" />
		</then>
	</if>

	<if>
		<not>
			<equals arg1="${noOrganizationsExist}" arg2="true" />
		</not>
		<then>
			<execute function="AssertVisible" locator1="UsersAndOrganizations#ORGANIZATION_TABLE_HEADER_PARENT_ORGANIZATION" />
		</then>
	</if>
</command>
--------------------------------------------------------------------------------------------------
I define the variable name "noOrganizationsExist" in order not to execute the function of "AssertVisible". So we can use the simpler navigation to organization tab and just assert the message info.

Please let me know if you have any questions.

Best,
Beck.

**Comment by brianwulbern** [comment]
@liuxingye Ah, my bad!  I'll just simplify the logic there then.  Double negatives are unnecessarily complex.

**Comment by brianwulbern** [comment]
See the updated pull here: https://github.com/evannagayama/liferay-portal/pull/726

**Comment by liuxingye** [comment]
@brianwulbern 
Thanks for the update.

Best,
Beck.

**Pull request closed without merging**
