### PR TITLE
master-qa-51330

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-51330
Please cherry-pick to 7.2.x

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @yunlinsun 

Macro PortletEntry.publish also includes Alert.viewSuccessMessage, I just added this step to the case. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77032

**Pull request closed without merging**
