### PR TITLE
master-qa-43436

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-43436

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by GinsonRen** [comment]
Hi @JoyceWang08211 ,

- Since "inputTemplateAddScreenFields" has been used in lots of macro/testcase, please add <if isset> condition in your case, thank you.
- Please use assertVisible for assert image display.

Please re-send your fix, thanks.

**Pull request closed without merging**
