### PR TITLE
master-qa-34099

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-34099

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
cc @GinsonRen

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@SylviaLuan 

- Typo for "deletePullCP", should be "deletePollCP".
- Under macro "deletePollCP", move the clarify of "key_pollsQuestionTitle" into Click(locator1 = "Polls#POLLS_TABLE_ACTION");
- According to the steps in LPS-72145, the poll should be display on living site, why did you use the function "AssertElementNotPresent"?
- For macro "viewPollOnLivingSite", this macro is not only for Living Site, you probably add navigator of living site if you want to make this specific for living staging. Or you can just use "viewPollPG".

Please re-send your fix, thanks.

**Pull request closed without merging**
