### PR TITLE
master-qa-45174

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-45174

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Pushed to AChiang.
https://github.com/austinchiang/liferay-portal/pull/344

**Comment by GinsonRen** [comment]
Pushed to AChiang.
https://github.com/austinchiang/liferay-portal/pull/344

**Pull request closed without merging**
