### PR TITLE
master-qa-42911

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-42911

### CODE REVIEW

**Comment by suilin** [comment]
@brianwulbern

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF  for @suilin 

Use upgrade macro for upgrade testcase instead of use batch of duplicate steps.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65485

**Pull request closed without merging**
