### PR TITLE
master-qa-37777

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-37777

@brianwulbern

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@liulukiwi Could you please make your new locator more specific? Like include the text "Use Small Image" into the checkbox xpath. Thanks.

**Pull request closed without merging**
