### PR TITLE
master-qa-52720

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52720

Please backport the fix to 7.2.x, thanks!

/cc @john-co

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81498

**Pull request closed without merging**
