### PR TITLE
LPS-150966 Error thrown and redirected to Instance Settings page when saving configurations in Instance Settings 

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-150966](https://issues.liferay.com/browse/LPS-150966).<br/><br/>Hi @GinsonRen, I am sending this to you per @tinatian's request. We are trying to determine if the cache I removed in this pull is still needed for performance.<br/><br/>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
cc @tinatian

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@drewbrokke @tinatian @dantewang There is about -6.55% regression on login performence testing.

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8607651 | 54072 | 286 | -
PR-620 | - | 50530 | 275 | -6.55%

**Pull request closed without merging**
