### PR TITLE
master-qa-41034-a

### PR DESCRIPTION
**Pull request by felix3508**
https://issues.liferay.com/browse/LRQA-41034

### CODE REVIEW

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66949

**Pull request closed without merging**
