### PR TITLE
master-qa-49102

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-49102

/cc @brianwulbern

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @SylviaLuan , I just edit your commit message and test case name. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73295

**Pull request closed without merging**
