### PR TITLE
[Login-performance-tuning] LPS-150103

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, please help run one login performance test. I noticed you may use BASELINE (2022-3-14 master head) to test. For the pr, it may be conflicted if using that baseline. You may use the latest master(or after the commit 0d523af065f69f47846b857fa95ecd7069310199) as baseline . Thanks.

cc @dantewang @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@yuhai Here is the result, I change the baseline to 3/25 master head:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BASELINE (2022-3-25 master head) | 628907d | 43344 | 281 |  
LPS-150103-pr2 | https://github.com/GinsonRen/liferay-portal/pull/592 | 43838 | 271 | 1.14%

**Comment by yuhai** [comment]
@GinsonRen, thanks.

**Pull request closed without merging**
