### PR TITLE
LRQA-51163, LRQA-51329, LRQA-51227, LRQA-51336 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-51163
https://issues.liferay.com/browse/LRQA-51329
https://issues.liferay.com/browse/LRQA-51227
https://issues.liferay.com/browse/LRQA-51336
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77070

**Pull request closed without merging**
