### PR TITLE
LPS-X-DL-1 The edit file page does not seem to use the DLAdminManagementToolbarDisplayContext

### PR DESCRIPTION
**Pull request by dantewang**
@GinsonRen Please run DL diff for it, thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:document

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by GinsonRen** [comment]
@dantewang 

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-9 master head) | f0a7a79b100c64e882b834ced172ba1f41778484 | 31483 | 243 |  
dantewang:LPS-X-DL-1 | https://github.com/GinsonRen/liferay-portal/pull/610 | 30251 | 368 | -3.91%

**Comment by GinsonRen** [comment]
@dantewang I re-run the baseline, and here is the new comparison:


Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-9 master head) | f0a7a79b100c64e882b834ced172ba1f41778484 | 29442 | 515 |  
dantewang:LPS-X-DL-1 | https://github.com/GinsonRen/liferay-portal/pull/610 | 30251 | 368 | 2.75%

**Pull request closed without merging**
