### PR TITLE
master-qa-50420

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-50420
Need to cherry-pick to 7.2.x.
7.1.x: https://github.com/GinsonRen/liferay-portal-ee/pull/1013
7.0.x: https://github.com/GinsonRen/liferay-portal-ee/pull/1014

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
@brianwulbern

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
The relevant failure is unrelated to my fix.
```
Target exception: java.lang.RuntimeException: No class header found in /opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/BaseProjectTemplatesTest.java
```
I will run `ci:test:relevant` on https://github.com/GinsonRen/liferay-portal-ee/pull/1013

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76445

**Pull request closed without merging**
