### PR TITLE
master-qa-48004

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-48004

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71001

**Pull request closed without merging**
