### PR TITLE
master-qa-50897

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-50897
Can be cherry pick to 7.2

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @HarryC0204 

Commit message should capitalize the first letter. I just edited your commit message. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78597

**Pull request closed without merging**
