### PR TITLE
 LRQA-40855,  LRQA-40480, LRQA-41165, LRQA-40478 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-40855
https://issues.liferay.com/browse/LRQA-40480
https://issues.liferay.com/browse/LRQA-41165
https://issues.liferay.com/browse/LRQA-40478

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:retest

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
SF for @liulukiwi 

- Edit two more categories to Build.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/59354

**Pull request closed without merging**
