### PR TITLE
master-qa-50168

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-50168

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
@GinsonRen This issue can be cherry pick to 7.2.x

**Comment by GinsonRen** [comment]
Hi @melodywu 

assertNotVisible - The element is existence but cannot be viewed on page.
assertElementNotPresent - The element is nonexistence.

The purpose of macro "viewTextFieldNotVisible" is make sure the xpath can be found in html but cannot be viewed on page. Your change makes the purpose totally different. This macro is also called by WorkflowForms.testcase, your change will affect other case as well.

Please re-send your fix. thanks.

**Pull request closed without merging**
