### PR TITLE
master | LRQA-45695

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-45695

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66305

**Pull request closed without merging**
