### PR TITLE
master-qa-28028

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-28028

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:retest

**Comment by GinsonRen** [comment]
@liuxingye 
- SF for locator that should be order as alphabetical in path file.
- Please ci:retest or leave a comment after fix the format issue.

**Comment by GinsonRen** [comment]
Pushed to BWulbern.
brianwulbern#48

**Comment by liuxingye** [comment]
@GinsonRen 
Got it, thanks.

**Pull request closed without merging**
