### PR TITLE
Master | LRQA-42521

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-42521

cc/ @brianwulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@Hanlf @GinsonRen,

Not really a _fix_, but we could consider combining all of the locators in NavBar.path that start with:
`//ul[contains(@class,'navbar-nav')]/li/a[contains(.,'`

to make a variable path like this:
`//ul[contains(@class,'navbar-nav')]/li/a[contains(.,'${key_navItem}')]`

That could get rid of 12 locators that would then be unnecessary.

**Comment by Hanlf** [comment]
I will take care of it, Thanks! @GinsonRen @brianwulbern

**Comment by Hanlf** [comment]
Hi @brianwulbern @GinsonRen
Since combining locators affect lots of testcases and macros, I will do this in another ticket:  https://issues.liferay.com/browse/LRQA-44799, thanks!

**Pull request closed without merging**
