### PR TITLE
master-qa-42919

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-42919

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@Songyuewen 
Good job! No test changes needed :)

**Comment by GinsonRen** [comment]
Sf for @Songyuewen 

Good Job! I just move the property under the test command.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64940

**Pull request closed without merging**
