### PR TITLE
master-qa-34099

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-34099

### CODE REVIEW

**Comment by SylviaLuan** [comment]
cc @GinsonRen

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66949

**Pull request closed without merging**
