### PR TITLE
master-qa-42912-1

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-42912

In order not messy up the exist branch named master-qa-42912, I named this branch as master-qa-42912-1 to add post-upgrade case for 7.0.4 and 7.0.10.6

/cc @brianwulbern

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65923

**Pull request closed without merging**
