### PR TITLE
master-qa-46890

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-46890

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69569

**Comment by GinsonRen** [comment]
SF for @melodywu 

Please resolve your sf error when ci:test:sf fail, I will do this time. Thanks,

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69569

**Pull request closed without merging**
