### PR TITLE
master-qa-43378

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-43378

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @yuwanyang 

- Add description of LPS
- Update locator "SIMPLE_PUBLICATION_DELETION" to include item name
- Update locator name
- Update variable name

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64994

**Pull request closed without merging**
