### PR TITLE
master-qa-47961

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-47961
master only

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Comment by yunlinsun** [comment]
@brianwulbern
Ginson is off today. Could you take a look at this pull when you have time? Thanks.

**Comment by brianwulbern** [comment]
yeah, i'll fetch it on my working branch

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71174

**Comment by brianwulbern** [comment]
ci:close

**Comment by brianwulbern** [comment]
@GinsonRen you can close this

**Pull request closed without merging**
