### PR TITLE
master-qa-43439-1

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-43439

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
cc @brianwulbern

**Comment by GinsonRen** [comment]
SF for @suilin 

- I updated the case name to StagingRemoteLiveWebContentWithManualChosenID.
- The property of test.name.skip.portal.instance should include testcase file name.
- I moved ID text input locator to WCEditWebcontent.path file.
- I add a new locator for assert the ID instead of using the checkbox one.

**Pull request closed without merging**
