### PR TITLE
master-qa-50044

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-50044

Able to cherry-pick to 72

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevan

**Comment by brianwulbern** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@Jeremy-Ch
A better commit message for this would be "Click add button before typing address".
I just edited your commit message. Thank you.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76626

**Pull request closed without merging**
