### PR TITLE
[Login-performance-tuning]  LPS-151077

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, please help run one login performance test and use the latest master as baseline. 

cc @dantewang, @tinatian

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
Hi @zhangyan0701, could you please check the test result if these errors are related with the pr?

Thanks.

**Comment by GinsonRen** [comment]
@yuhai Here is the result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | a97e8b8 | 46189 | 269 | -
LPS-151077-pr2 | https://github.com/GinsonRen/liferay-portal/pull/598 | 48017 | 268 | 3.96%

**Comment by zhangyan0701** [comment]
**There are some related issues:**

**1.  Fragments or widgets fail to display in Content page or page template.**
Steps:
- Add a new content page.
- In edit mode of the page, add a fragment or widget, publish the page.
- Edit the page again.
- Assert error in page.
fragment
Example test: https://testray.liferay.com/home/-/testray/case_results/1660340596
Console: https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/918/functional-tomcat90-mysql57-jdk8/1/0/jenkins-console.txt.gz?authuser=0

**2. Sites that based on Masterclass and Team Extranet are blank.**
Steps:
-  Go to Control Panel > Sites.
- Add a new site, select Masterclass or Team Extranet template.
- Go to the new site.
- Home page is blank. And error in console:
masterclass

```
     [exec] 2022-04-11 02:56:17.784 ERROR [http-nio-8080-exec-8][IncludeTag:128] Curr
![masterclass](https://user-images.githubusercontent.com/25576873/162942430-11b553e9-48a0-4233-b6fe-42c044060087.jpg)
ent URL /en/web/test-masterclass-name/home?p_l_mode=search generates exception: java.util.ConcurrentModificationException
     [exec] java.util.ConcurrentModificationException: null
```
Example test: https://testray.liferay.com/home/-/testray/case_results/1660343709
Console: https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/918/functional-tomcat90-mysql57-jdk8/2/20/jenkins-console.txt.gz?authuser=0

**3. Some integration tests failed with java.lang.NullPointerException:**

- https://testray.liferay.com/home/-/testray/case_results/1660342594
https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/918/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0

- https://testray.liferay.com/home/-/testray/case_results/1660342531
https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/918/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0

- https://testray.liferay.com/home/-/testray/case_results/1660342614
https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/918/modules-integration-mysql57-jdk8/0/15/jenkins-console.txt.gz?authuser=0

**Comment by yuhai** [comment]
@GinsonRen thanks. I resend it to https://github.com/GinsonRen/liferay-portal/pull/601

**Pull request closed without merging**
