### PR TITLE
master-qa-43303

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-43303

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @liulukiwi 

- Move the refresh to testcase.

**Comment by GinsonRen** [comment]
Pushed to Bchan.
https://github.com/brianchandotcom/liferay-portal/pull/62798

**Pull request closed without merging**
