### PR TITLE
master-qa-50872

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-50872
Need to cherry-pick to 7.2.x
7.1.x: https://github.com/GinsonRen/liferay-portal-ee/pull/1009

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76395
https://github.com/brianchandotcom/liferay-portal-ee/pull/25712

**Pull request closed without merging**
