### PR TITLE
LRQA-50335, LRQA-50320, LRQA-50337 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-50335
https://issues.liferay.com/browse/LRQA-50320
https://issues.liferay.com/browse/LRQA-50337
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/75971

**Pull request closed without merging**
