### PR TITLE
master-qa-45489

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-45489

/ cc @brianwulbern

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @Sharryxue 

Correct the ticket number in commit message.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66209

**Pull request closed without merging**
