### PR TITLE
master-qa-47967

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-47967
master only

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Comment by GinsonRen** [comment]
@yunlinsun This issue will be fixed in LRQA-48001, only keep the updating for METADATA_TAGS xpath. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71320

**Pull request closed without merging**
