### PR TITLE
LRQA-50945, LRQA-51247,LRQA-51246,LRQA-51228 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-50945
https://issues.liferay.com/browse/LRQA-51247
https://issues.liferay.com/browse/LRQA-51246
https://issues.liferay.com/browse/LRQA-51228
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @Songyuewen ,

For LRQA-51228, please make sure the original purpose of StagingBlogsPG, according to the above steps, we should see the Blogs Entry Title 2 on live site. The navigator is correct. Please double check if it is a bug or a test fix. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76791

**Pull request closed without merging**
