### PR TITLE
LRQA-39770, LRQA-39962, LRQA-39963 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-39770
https://issues.liferay.com/browse/LRQA-39962
https://issues.liferay.com/browse/LRQA-39963

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test

**Comment by GinsonRen** [comment]
ci:retest

**Comment by GinsonRen** [comment]
@Lori-Liu Please re-send LRQA-39962. Thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/59547

**Pull request closed without merging**
