### PR TITLE
master | LRQA-42609

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-42609

cc/ @Brianwulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to AChiang.
https://github.com/austinchiang/liferay-portal/pull/330

**Pull request closed without merging**
