### PR TITLE
LPS-X Add an index to shortcut earlier: 1) if there's no entry for the encoded key, add the key to the index; 2) any more queries for the same key will be shortcut 3) the key is removed from the index if there's database modification for the key

### PR DESCRIPTION
**Pull request by dantewang**
@GinsonRen Please run a performance comparison, thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@GinsonRen Force pushed. If you have run this pull, please re-pull and re-run.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@dantewang Here is the result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BASELINE (2022-3-14 master head) | e34290f69c2 | 42375 | 273 |  
LPS-X-PLO | https://github.com/GinsonRen/liferay-portal/pull/591 | 43893 | 274 | 3.58%

**Pull request closed without merging**
