### PR TITLE
[DL Performance tuning] LPS-DL1 make three jsp as jspf 

### PR DESCRIPTION
**Pull request by yuhai**
@GinsonRen, please run one dl performance test. 

cc @dantewang, @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Please create a ticket and send this pull to liferay-core-infra directly. Let's run CI there. Making JSP into JSPF is almost always an optimization. Just make sure the functionality is not affected.

**Comment by dantewang** [comment]
ci:stop

**Comment by GinsonRen** [comment]
@yuhai Here is the DL result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-16 master head) | 41fa9fed94f20c40a4bcf5febb6dd3b5972d2d23 | 29199 | 512 |  
yuhai:LPS-DL1 | https://github.com/GinsonRen/liferay-portal/pull/612 | 28391 | 243 | -2.77%

**Comment by GinsonRen** [comment]
@yuhai I re-run the test base on 5-17 master head, here is the result:


Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
Baseline(5-17 master head) | a46b569501304cd4a45ff072f5846e2f2fbc9c11 | 30987 | 247 |  
yuhai:LPS-DL1 | https://github.com/GinsonRen/liferay-portal/pull/612 | 31424 | 230 | 1.41%

**Pull request closed without merging**
