### PR TITLE
LRQA-49756, LRQA-50936, LRQA-50074 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-49756
https://issues.liferay.com/browse/LRQA-50936
https://issues.liferay.com/browse/LRQA-50074
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @Songyuewen 
For LRQA-50074:

- Your fix of locator also affect testcases WorkflowForms#ViewDateAssetDetails and WorkflowForms#ViewEntryWithConditionalVisibilityFromSelectAndRadio in macro Form.configureWorkflow, please double check them.
- Macro clickSubmitForPublication affect too many testcases, make sure all "submit for publication" button has changed to "submit", otherwise, this change is too risky.
- Macro clickSubmitForPublication should only use for click "Submit for Publication" button, click "Submit" button under macro clickSubmitForPublication doesn't make sense.
- There are some macro you may can use it directly like "FormPortlet.clickSubmit" and "Form.submitFormPublish".

Please re-send your fix, thanks.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/76395
https://github.com/brianchandotcom/liferay-portal-ee/pull/25712

**Pull request closed without merging**
