### PR TITLE
LRQA-51850, LRQA-51851, LRQA-51845, LRQA-51849 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-51850
https://issues.liferay.com/browse/LRQA-51851
https://issues.liferay.com/browse/LRQA-51845
https://issues.liferay.com/browse/LRQA-51849
Can cherrypick to 7.2.x

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78107

**Pull request closed without merging**
