### PR TITLE
master-qa-25396

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-25396

### CODE REVIEW

**Comment by GinsonRen** [comment]
@liuxingye 
Don't use constant variable under macro file. Thank you.

**Comment by GinsonRen** [comment]
Pushed to BWulbern.
brianwulbern#155

**Comment by liuxingye** [comment]
@GinsonRen

**Comment by liuxingye** [comment]
Got it. Thanks.

**Pull request closed without merging**
