### PR TITLE
master-qa-44511

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-44511

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@yuwanyang  Please fix the source-format issue and update the macro fix. Thanks.

**Pull request closed without merging**
