### PR TITLE
master-qa-43436

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-43436

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @JoyceWang08211 
- Update value of templateSmallImage as true.
- Update macro inputTemplateAddScreenFields for avoid needless steps.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64994

**Pull request closed without merging**
