### PR TITLE
master-qa-51477

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-51477
Please cherry-pick to 7.2.x, thanks.

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77130

**Pull request closed without merging**
