### PR TITLE
master-qa-27149

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-27149

### CODE REVIEW

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Fetched onto working branch.  @Sharryxue or @GinsonRen please close this pull, thanks.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42667
https://github.com/brianchandotcom/liferay-portal/pull/42668

**Comment by Sharryxue** [comment]
Thanks @brianwulbern and @GinsonRen

**Pull request closed without merging**
