### PR TITLE
LRQA-34128 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-34128

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test

**Comment by Hanlf** [comment]
Repushed the pull to fix the SF issue.

**Comment by GinsonRen** [comment]
SF for @JoyceWang08211 @Hanlf 

- Match the priority of the LPS.
- Update commit message to "Add testcase for remote staging of blogs"

**Comment by GinsonRen** [comment]
Pushed to BWulbern.
brianwulbern#201

**Pull request closed without merging**
