### PR TITLE
Master | LRQA-44799

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-44799

cc / @brianwulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@Hanlf @GinsonRen 

Instead of `NAV_BAR_GENERAL`, we could probably go with just `GENERAL` or use `ANY_NAV_BAR`, following the pattern in MenuItem.path.  But since the path is already in NavBar.path, the name can be simplified and less redundant.

**Comment by Hanlf** [comment]
@brianwulbern 
Resend it with locator named ANY_NAV_BAR, thanks！

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@Hanlf please run poshi-validation to see the error locally, then you can fix the error above ^

**Comment by Hanlf** [comment]
Thanks @brianwulbern 
I resend a pull [here](https://github.com/GinsonRen/liferay-portal/pull/304), cause I found there is an existing locator `NavBar#NAV_ITEM_LINK` and macro `Navigator#gotoNavItem`.

**Pull request closed without merging**
