### PR TITLE
master-qa-41417

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-41417

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test

**Comment by liulukiwi** [comment]
Hi @GinsonRen , the ci failures are not related to this pull.

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/62120

**Pull request closed without merging**
