### PR TITLE
 LRQA-42169 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-42169

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test

**Comment by liulukiwi** [comment]
Hi @GinsonRen , the SF error is related to my commits, but I don't know if I should make some changes, could you take a look at that? Thanks!

**Comment by GinsonRen** [comment]
SF for @liulukiwi 
Remove the extra space.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/61698

**Pull request closed without merging**
