### PR TITLE
LRQA-43349, LRQA-43135 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-43349
https://issues.liferay.com/browse/LRQA-43135

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to Bchan.
https://github.com/brianchandotcom/liferay-portal/pull/62798

**Pull request closed without merging**
