### PR TITLE
master-qa-42927

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-42927

/cc @brianwulbern

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test

**Comment by brianwulbern** [comment]
`Save the configuration in portal file portal-setup-wizard.properties successfully`

is probably better phrased:

`The configuration was saved successfully in portal-setup-wizard.properties!`

**Comment by brianwulbern** [comment]
And we should probably make sure the test fails after the fail message (make it do something it can't)

@GinsonRen @Sharryxue

**Comment by GinsonRen** [comment]
@brianwulbern  Echo fail message will make the poshi test case fail, we don't need to do something else.

**Comment by GinsonRen** [comment]
SF for @Sharryxue 
- Skip the case from portal instance.
- Updated the echo message as Brian's suggestion.
- Update the case name to ViewConfiguredSetupWizardValue.

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64994

**Pull request closed without merging**
