### PR TITLE
LPS-X Hibernate 5: bring back the QueryCachePlan optimization as we still see a lot of BLOCKED threads on the MetamodelImpl#getImportedClassName class loading logic. Compared to the optimization for Hibernate 3, we only need to replace the "metamodel" field in the session factory object because the logic is now in MetamodelImpl#getImportedClassName and QueryCachePlan obtains the metamodel from the session factory. We can't use a Integrator to do this because Integrators are called by the session factory constructor before the metamodel is created.

### PR DESCRIPTION
**Pull request by dantewang**
@GinsonRen Please run a performance comparison for all test cases (but blog first) on top of the latest master. FYI @yuhai @tinatian We need to bring this optimization back.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? This is related to Hibernate so please also trigger any test suites you think necessary.

**Comment by dantewang** [comment]
@GinsonRen Any update for the performance tests?

**Comment by zhangyan0701** [comment]
ci:test:backend-hypersonic

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
No regressions found. All failures are unrelated.

**Comment by dantewang** [comment]
@GinsonRen Please post to https://github.com/liferay-core-infra/liferay-portal/pull/660 when you get the results.

**Pull request closed without merging**
