### PR TITLE
master-qa-31088

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-31088

@brianwulbern

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
SF for @JoyceWang08211 ,

- The variable declaration of "key_dmDocumentURL" is not necessary in macro "BlogsEntry#viewDMLink".
- Move "addLinkViaBrowseButton" to BlogEntry#addEntryExternalLinkViaBrowseButton.
- Update "viewDMLink" as "viewEntryExternalURL".
- Update locator CONTENT_LINK.
- Re-order TEXT_FORMATTING_LINK_BROWSE_BUTTON.

**Comment by GinsonRen** [comment]
Pushed to AChiang.
https://github.com/austinchiang/liferay-portal/pull/330

**Pull request closed without merging**
