### PR TITLE
LPS-X Create BufferedIncrementThreadLocal to replace ProxyModeThreadLocal usage in BufferedIncrementProcessor

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @dantewang Here is the diff result of mb:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5e223c8 | 6830 | 195 | 366 | -
PR-574 | TRUE | 6844 | 147 | 322 | 0.20%
PR-574 | FALSE | 6849 | 144 | 293 | 0.28%

**Comment by dantewang** [comment]
@GinsonRen Could you run an extra test on wiki with `TRUE` in the class to see if it fixes the exception you mentioned in the email?

**Comment by dantewang** [comment]
ci:test:relevant

**Pull request closed without merging**
