### PR TITLE
master-qa-51433

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-51433

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
@GinsonRen This case can be cherry pick to 7.2.x

**Comment by GinsonRen** [comment]
No test changes needed :)

**Comment by GinsonRen** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78107

**Pull request closed without merging**
