### PR TITLE
master-qa-23054_2

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-23054

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:retest

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40867
https://github.com/brianchandotcom/liferay-portal/pull/40868

**Comment by brianwulbern** [comment]
@Hanlf @GinsonRen please close this pr. Thanks!

**Pull request closed without merging**
