### PR TITLE
Master qa 52825

### PR DESCRIPTION
**Pull request by dellawang**
https://issues.liferay.com/browse/LRQA-52825

### CODE REVIEW

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by dellawang** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@dellawang 

- Please make your code done before your pull request to your reviewer, revert commit should not in your pull request.
- Don't use for loop if there is only one variable.
- Don't use /* */ in your code.
- Please add a template for the structure before add web content base on it.
- After staging publish, please assert that web content already be published.
- For AssertConsoleTextNotPresent function, please use small pies of error message instead of a long sentence.

Please re-send this, thanks.

**Pull request closed without merging**
